name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./ripple_sync/Dockerfile
        push: true
        tags: |
          ghcr.io/jkmn-projects/ripple_sync_frontend:${{ github.run_number }}
          ghcr.io/jkmn-projects/ripple_sync_frontend:latest
